version: '3.4'
 
services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_SITE_BASEURL: /mongo-express/
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
    restart: always